app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, StringField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length, Email


class PostForm(FlaskForm):
    content = TextAreaField(
        "게시글 작성", validators=[DataRequired("내용을 입력해주세요")], render_kw={"rows": 20}
    )
    submit = SubmitField("등록", render_kw={"class": "btn btn-secondary"})


class EditProfileForm(FlaskForm):
    email = StringField(
        "이메일",
        validators=[DataRequired(), Length(1, 64), Email()],
        render_kw={"readonly": True},
    )
    name = StringField("이름", validators=[DataRequired(), Length(1, 64)])
    abount_me = TextAreaField("상태메세지")
    gender = SelectField("성별", choices=[("F", "여자"), ("M", "남자")])
    birth = DateField("생년월일")
    location = StringField("지역")
    job = StringField("직업")
    submit = SubmitField("수정", render_kw={"class": "btn btn-secondary"})

app/user/__init__.py
from flask import Blueprint

user = Blueprint("user", __name__)

from . import views

app/user/views.py
from . import user
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    current_app,
    flash,
    jsonify,
    make_response,
    session,
)
from flask_login import login_required, current_user
from ..models import User, Post, Comment, PostLike
from .forms import PostForm, EditProfileForm
from ..main.forms import CommentForm
from .. import db


@user.route("/<int:user_id>")
def user_page(user_id):
    form = CommentForm()
    user = User.query.get_or_404(user_id)
    page = request.args.get("page", 1, type=int)

    post = None
    post_id = request.args.get("postId", None)
    if post_id:
        post = Post.query.get(post_id)

    tab_status = request.cookies.get("tab_status", "post")
    if tab_status == "post":
        query = user.posts.filter_by(deleted=False).order_by(Post.created_at.desc())
    else:  # like
        query = (
            Post.query.join(PostLike, Post.like_users)
            .join(User, PostLike.user)
            .filter(User.id == user_id)
            .order_by(Post.created_at.desc())
        )
    pagination = query.paginate(
        page, per_page=current_app.config["POSTS_PER_PAGE"], error_out=False
    )
    posts = pagination.items
    return render_template(
        "user.html",
        user=user,
        posts=posts,
        pagination=pagination,
        form=form,
        post=post,
        tab_status=tab_status,
    )


@user.route("/post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        post = Post(content=form.content.data, user=user)
        db.session.add(post)
        db.session.commit()
        flash("게시글이 작성되었습니다.", "success")
        return redirect(url_for("user.user_page", user_id=current_user.id))

    return render_template("user/post.html", form=form)


@user.route("/profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = EditProfileForm(obj=current_user._get_current_object())
    if form.validate_on_submit():
        user = current_user._get_current_object()
        form.populate_obj(user)
        db.session.commit()
        flash("프로필이 수정 되었습니다.", "success")
        return redirect(url_for("user.user_page", user_id=current_user.id))
    return render_template("user/profile.html", form=form)


@user.route("/post/<int:post_id>/<string:end_point>/<int:page>", methods=["POST"])
@login_required
def add_comment(post_id, end_point, page=1):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    comment = Comment(
        content=form.content.data.strip(), user=current_user._get_current_object()
    )
    post.comments.append(comment)
    db.session.commit()
    flash("댓글이 추가되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post.id)
    )


@user.route("/comment/<int:comment_id>/<string:end_point>/<int:page>", methods=["POST"])
@login_required
def edit_comment(comment_id, end_point, page=1):
    form = CommentForm()
    comment = Comment.query.get(comment_id)
    post_id = comment.post.id
    comment.content = form.content.data.strip()
    db.session.commit()
    flash("댓글이 수정되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post_id)
    )


@user.route(
    "/comment/delete/<int:comment_id>/<string:end_point>/<int:page>", methods=["POST"]
)
@login_required
def delete_comment(comment_id, end_point, page=1):
    comment = Comment.query.get(comment_id)
    post_id = comment.post.id
    comment.deleted = True
    db.session.commit()
    flash("댓글이 삭제되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post_id)
    )


@user.route("/post/<int:post_id>/like", methods=["POST", "FETCH"])
def update_post_like_status(post_id):
    post = Post.query.get(post_id)
    if request.method == "POST":
        if current_user.is_liked_post(post):
            current_user.unlike_post(post)
        else:
            current_user.like_post(post)
        db.session.commit()
        return jsonify({"isLiked": current_user.is_liked_post(post)})
    else:
        return jsonify({"count": post.like_users.count()})


@user.route("/comment/<int:comment_id>/like", methods=["POST", "FETCH"])
def update_comment_like_status(comment_id):
    comment = Comment.query.get(comment_id)
    if request.method == "POST":
        if current_user.is_liked_comment(comment):
            current_user.unlike_comment(comment)
        else:
            current_user.like_comment(comment)
        db.session.commit()
        return jsonify({"isLiked": current_user.is_liked_comment(comment)})
    else:
        return jsonify({"count": comment.like_users.count()})


@user.route("/tab/cookie", methods=["GET"])
def update_tab_cookie():
    user_id = request.args.get("user_id")
    tab_status = request.args.get("status", "post", type=str)
    resp = make_response(redirect(url_for("user.user_page", user_id=user_id)))
    resp.set_cookie("tab_status", tab_status, max_age=30 * 24 * 60 * 60)
    return resp

app/templates/user/_comment_delete_modal.html
<div class="modal fade" id="comment-delete-{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">댓글 삭제</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <form
        action="{{url_for('user.delete_comment', comment_id=comment.id, end_point=end_point, page=pagination.page)}}"
        method="post">
        <div class="form-group">
          <div>댓글을 삭제하시겠습니까?</div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">취소</button>
          <button type="submit" class="btn btn-secondary">삭제 </button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>

app/templates/user/_comment_edit_modal.html
<div class="modal fade" id="comment-edit-{{comment.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">댓글 수정</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <form
        action="{{url_for('user.edit_comment', comment_id=comment.id, end_point=end_point, page=pagination.page)}}"
        method="post">
        {{ form.hidden_tag() }}
        {{ render_hidden_errors(form) }}
        <div class="form-group">
          <label class="col-form-label">내용</label>
          {{form.content(value=comment.content)}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">취소</button>
          {{form.submit}}
        </div>
      </form>
    </div>
  </div>
</div>
</div>

app/templates/user/_comments.html
<div id="post-{{post.id}}" class="collapse pt-1 pb-1 pr-3 pl-3 mb-2 comment-body" data-parent="#accordionExample"
  aria-labelledby="post-card-header-{{post.id}}">
  {% if post.comments.filter_by(deleted=False).all() %}
  {% for comment in post.comments.filter_by(deleted=False).all() %}
  <hr class="my-1">
  <div class="comment-thumbnail comment-author mt-1">
    <img class="rounded-circle profile-thumbnail"
      src="{{ url_for('static', filename='images/resources/detail-gold1.jpg') }}">
    {{comment.user.name}}
    {% if current_user == comment.user and end_point == 'main.index'%}
    <span class="badge badge-primary mr-1 ml-1">나의 댓글</span>
    {% endif %}
    <a class="float-right text-muted mt-1 mr-1" {%if current_user.is_authenticated %}
    onclick="update_comment_like_button({{comment.id}});" {% else %} onclick="alert('로그인 후 이용해 주세요')" {%
    endif %}>
      {% if current_user.is_authenticated and current_user.is_liked_comment(comment) %}
      <img id="comment-like-{{comment.id}}" src="{{url_for('static', filename='svg/like-fill.svg')}}" alt="" style="width:15px; height:15px;">
      {% else %}
      <img id="comment-like-{{comment.id}}" src="{{url_for('static', filename='svg/like.svg')}}" alt="" style="width:15px; height:15px;">
      {% endif %}
      <span id="comment-like-button-{{comment.id}}" style="font-size:13px;">{{comment.like_users.count()}}명</span>
    </a>
  </div>
  <div class="comment-date pl-3">
    {{comment.updated_at|datetime or comment.created_at|datetime}}
  </div>
  {% if current_user == comment.user %}
  <div class="comment-date pl-2"><a data-toggle="modal" data-target="#comment-delete-{{comment.id}}"
      style="color: grey;">삭제</a></div>
  <div class="comment-date pl-2"><a data-toggle="modal" data-target="#comment-edit-{{comment.id}}"
      style="color: grey;">수정</a></div>
  {% endif %}
  {% if comment.content|count >= 100 %}
  <div class="comment-date pl-1"><a id="comment-{{comment.id}}-more"
      onclick="show_more_comment({{comment.id}});">더보기</a></div>
  {% endif %}
  <div class="comment-content mt-1 text-truncate" id="comment-body-{{comment.id}}">
    &nbsp;&nbsp;&nbsp;&nbsp;{{comment.content}}
  </div>
  {% include 'user/_comment_edit_modal.html' %}
  {% include 'user/_comment_delete_modal.html' %}
  {% endfor %}
  {% endif %}
  {% if current_user.is_authenticated %}
  <div class="mt-3">
    <hr>
    <form action="{{url_for('user.add_comment', post_id=post.id, end_point=end_point, page=pagination.page)}}"
      method="post">
      {{ form.hidden_tag() }}
      {{ render_hidden_errors(form) }}
      <div class="form-group row">
        <div class="col-md-10">
          {{form.content}}
        </div>
        <div class="col-md-2">
          {{form.submit}}
        </div>
      </div>
    </form>
  </div>
  {% endif %}
</div>

app/templates/user/_posts.html
<div class="accordion mt-3" id="accordionExample">
    {% for post in posts %}
    <div class="card">
        <div class="mt-3 mb-3 pr-3 pl-3" id=post-card-header-{{post.id}}>
            <div class="post-thumbnail pr-3">
                <img class="rounded-circle profile-thumbnail"
                    src="{{ url_for('static', filename='images/resources/detail-gold1.jpg') }}">
            </div>
            <div class="post-content">
                <div class="post-date">{{post.created_at|datetime}}</div>
                <div class="post-author">&nbsp;&nbsp;<a
                        href="{{url_for('user.user_page', user_id=post.user.id)}}">{{post.user.name}}
                    </a>
                    {% if current_user == post.user and end_point == 'main.index' %}
                    &nbsp;&nbsp;<span class="badge badge-secondary">나의 게시글</span>
                    {% endif %}
                </div>
                <div class="post-body">&nbsp;&nbsp;&nbsp;{{ post.content }}</div>
                <div class="post-footer">
                    <button class="post-like-button-{{post.id}} btn btn-sm mb-1" {%if current_user.is_authenticated %}
                        onclick="update_post_like_button({{post.id}});" {% else %} onclick="alert('로그인 후 이용해 주세요')" {%
                        endif %}>
                        {% if current_user.is_authenticated and current_user.is_liked_post(post) %}
                        <img id="post-like-{{post.id}}" src="{{url_for('static', filename='svg/like-fill.svg')}}"
                            alt="">
                        {% else %}
                        <img id="post-like-{{post.id}}" src="{{url_for('static', filename='svg/like.svg')}}" alt="">
                        {% endif %}
                        <p>좋아요 {{post.like_users.all()|count}}</p>
                    </button>
                    <button class="btn btn-sm mb-1" id="post-{{post.id}}" type="button" data-toggle="collapse"
                        data-target="#post-{{post.id}}" aria-expanded="true" aria-controls="post-{{post.id}}">
                        <img src="{{url_for('static', filename='svg/chat-square-text.svg')}}" alt="">
                        <p>댓글 {{post.comments.filter_by(deleted=False).all()|count}}</p>
                    </button>
                </div>
            </div>
            {% include 'user/_comments.html' %}
        </div>
    </div>
    {% endfor %}
</div>

app/templates/user/post.html
{% extends "base.html" %}
{% block title %}Heej{% endblock %}

{% block page_content %}
<div class="row mt-3">
	<div class="col-md-12">
		<form action="" method="post">
            {{ form.hidden_tag() }}
            {{ render_hidden_errors(form) }}
            {{ render_field(form.content) }}
            {{ render_field(form.submit) }}
            <a href="{{url_for('user.user_page', user_id=current_user.id)}}" class="btn btn-outline-secondary">돌아가기</a>
        </form>
	</div>
</div>
{% endblock %}

app/templates/user/profile.html
{% extends "base.html" %}
{% block title %}Heej{% endblock %}

{% block page_content %}
<div class="row mt-5">
	<div class="col-md-7">
		<form action="" method="post">
            {{ form.hidden_tag() }}
            {{ render_hidden_errors(form) }}
            {{ render_field(form.email) }}
            {{ render_field(form.name) }}
            {{ render_field(form.abount_me) }}
            {{ render_field(form.gender) }}
            {{ render_field(form.birth) }}
            {{ render_field(form.location) }}
            {{ render_field(form.job) }}
            {{ render_field(form.submit) }}
            <a href="{{url_for('user.user_page', user_id=current_user.id)}}" class="btn btn-outline-secondary">돌아가기</a>
        </form>
	</div>
</div>
{% endblock %}