app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, StringField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length, Email


class PostForm(FlaskForm):
    content = TextAreaField(
        "게시글 작성", validators=[DataRequired("내용을 입력해주세요")], render_kw={"rows": 20}
    )
    submit = SubmitField("등록", render_kw={"class": "btn btn-secondary"})


class EditProfileForm(FlaskForm):
    email = StringField(
        "이메일",
        validators=[DataRequired(), Length(1, 64), Email()],
        render_kw={"readonly": True},
    )
    name = StringField("이름", validators=[DataRequired(), Length(1, 64)])
    abount_me = TextAreaField("상태메세지")
    gender = SelectField("성별", choices=[("F", "여자"), ("M", "남자")])
    birth = DateField("생년월일")
    location = StringField("지역")
    job = StringField("직업")
    submit = SubmitField("수정", render_kw={"class": "btn btn-secondary"})

app/user/__init__.py
from flask import Blueprint

user = Blueprint("user", __name__)

from . import views

app/user/views.py
from . import user
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    current_app,
    flash,
    jsonify,
    make_response,
    session,
)
from flask_login import login_required, current_user
from ..models import User, Post, Comment, PostLike
from .forms import PostForm, EditProfileForm
from ..main.forms import CommentForm
from .. import db


@user.route("/<int:user_id>")
def user_page(user_id):
    form = CommentForm()
    user = User.query.get_or_404(user_id)
    page = request.args.get("page", 1, type=int)

    post = None
    post_id = request.args.get("postId", None)
    if post_id:
        post = Post.query.get(post_id)

    tab_status = request.cookies.get("tab_status", "post")
    if tab_status == "post":
        query = user.posts.filter_by(deleted=False).order_by(Post.created_at.desc())
    else:  # like
        query = (
            Post.query.join(PostLike, Post.like_users)
            .join(User, PostLike.user)
            .filter(User.id == user_id)
            .order_by(Post.created_at.desc())
        )
    pagination = query.paginate(
        page, per_page=current_app.config["POSTS_PER_PAGE"], error_out=False
    )
    posts = pagination.items
    return render_template(
        "user.html",
        user=user,
        posts=posts,
        pagination=pagination,
        form=form,
        post=post,
        tab_status=tab_status,
    )


@user.route("/post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        user = current_user._get_current_object()
        post = Post(content=form.content.data, user=user)
        db.session.add(post)
        db.session.commit()
        flash("게시글이 작성되었습니다.", "success")
        return redirect(url_for("user.user_page", user_id=current_user.id))

    return render_template("user/post.html", form=form)


@user.route("/profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = EditProfileForm(obj=current_user._get_current_object())
    if form.validate_on_submit():
        user = current_user._get_current_object()
        form.populate_obj(user)
        db.session.commit()
        flash("프로필이 수정 되었습니다.", "success")
        return redirect(url_for("user.user_page", user_id=current_user.id))
    return render_template("user/profile.html", form=form)


@user.route("/post/<int:post_id>/<string:end_point>/<int:page>", methods=["POST"])
@login_required
def add_comment(post_id, end_point, page=1):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    comment = Comment(
        content=form.content.data.strip(), user=current_user._get_current_object()
    )
    post.comments.append(comment)
    db.session.commit()
    flash("댓글이 추가되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post.id)
    )


@user.route("/comment/<int:comment_id>/<string:end_point>/<int:page>", methods=["POST"])
@login_required
def edit_comment(comment_id, end_point, page=1):
    form = CommentForm()
    comment = Comment.query.get(comment_id)
    post_id = comment.post.id
    comment.content = form.content.data.strip()
    db.session.commit()
    flash("댓글이 수정되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post_id)
    )


@user.route(
    "/comment/delete/<int:comment_id>/<string:end_point>/<int:page>", methods=["POST"]
)
@login_required
def delete_comment(comment_id, end_point, page=1):
    comment = Comment.query.get(comment_id)
    post_id = comment.post.id
    comment.deleted = True
    db.session.commit()
    flash("댓글이 삭제되었습니다.", "success")
    return redirect(
        url_for(end_point, user_id=comment.post.user.id, page=page, postId=post_id)
    )


@user.route("/post/<int:post_id>/like", methods=["POST", "FETCH"])
def update_post_like_status(post_id):
    post = Post.query.get(post_id)
    if request.method == "POST":
        if current_user.is_liked_post(post):
            current_user.unlike_post(post)
        else:
            current_user.like_post(post)
        db.session.commit()
        return jsonify({"isLiked": current_user.is_liked_post(post)})
    else:
        return jsonify({"count": post.like_users.count()})


@user.route("/comment/<int:comment_id>/like", methods=["POST", "FETCH"])
def update_comment_like_status(comment_id):
    comment = Comment.query.get(comment_id)
    if request.method == "POST":
        if current_user.is_liked_comment(comment):
            current_user.unlike_comment(comment)
        else:
            current_user.like_comment(comment)
        db.session.commit()
        return jsonify({"isLiked": current_user.is_liked_comment(comment)})
    else:
        return jsonify({"count": comment.like_users.count()})


@user.route("/tab/cookie", methods=["GET"])
def update_tab_cookie():
    user_id = request.args.get("user_id")
    tab_status = request.args.get("status", "post", type=str)
    resp = make_response(redirect(url_for("user.user_page", user_id=user_id)))
    resp.set_cookie("tab_status", tab_status, max_age=30 * 24 * 60 * 60)
    return resp

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="page-item disabled"{% endif %}>
        <a class="page-link" href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="page-item active">
                <a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#" class="page-link">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="page-item disabled"{% endif %}>
        <a class="page-link" href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
  </ul>
{% endmacro %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/fav.png') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mycss.css') }}">
    {% block styles %}
    <!-- Bootstrap CSS -->
    {{ bootstrap.load_css() }}
    {% endblock %}

    <title>Heej</title>
    {% endblock %}

    {% from "bootstrap/form.html" import render_form, render_field, render_hidden_errors %}
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Heej</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.index')}}">홈</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('user.user_page', user_id=current_user.id)}}">마이페이지</a>
                    </li>
                    {% endif %}
                </ul>
                {% if current_user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            계정
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('auth.logout')}}">로그아웃</a>
                            <a class="dropdown-item" href="{{url_for('auth.password_reset_request')}}">비밀번호 변경</a>
                        </div>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            계정
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('auth.login')}}">로그인</a>
                            <a class="dropdown-item" href="{{url_for('auth.register')}}">회원가입</a>
                        </div>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}
    <!-- Your page content -->
    {% block content %}
    <div class="container">
        {% if not current_user.is_authenticated and request.blueprint != 'auth' %}
        <div class="alert alert-danger">
            로그인 후 이용해 주세요.
        </div>
        {% endif %}
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert-flash alert alert-{{ category }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
    {% endblock %}

    {% block scripts %}
    <!-- Optional JavaScript -->
    {{ bootstrap.load_js() }}
    <script>
        $(document).ready(function () {
            $('#post-{% if post %}{{post.id}}{%else%}{{""}}{% endif %}').click()
            setTimeout(hide_alert, 3000);
        });
        function hide_alert() {
            $('.alert-flash').hide();
        }
        function show_more_comment(comment_id) {
            $('#comment-body-' + String(comment_id)).removeClass('text-truncate');
            $('#comment-' + String(comment_id) + '-more').text('감추기')
            $('#comment-' + String(comment_id) + '-more').attr('onclick', 'hide_comment(' + String(comment_id) + ');')
        }
        function hide_comment(comment_id) {
            $('#comment-body-' + String(comment_id)).addClass('text-truncate');
            $('#comment-body-' + String(comment_id)).addClass('text-truncate');
            $('#comment-body-' + String(comment_id)).addClass('text-truncate');
            $('#comment-' + String(comment_id) + '-more').text('더보기')
            $('#comment-' + String(comment_id) + '-more').attr('onclick', 'show_more_comment(' + String(comment_id) + ');')
        }

        function update_post_like_count(post_id) {
            $.ajax({
                url: "/user/post/" + post_id + "/like",
                type: "FETCH",
                dataType: "json",
                success: function (result) {
                    $('button.post-like-button-' + String(post_id) + ' > p').text("좋아요 " + String(result.count))
                }

            });
        }

        function update_post_like_button(post_id) {
            if (Boolean('{{current_user.is_authenticated}}')) {
                $.ajax({
                    url: "/user/post/" + post_id + "/like",
                    type: "POST",
                    dataType: "json",
                    success: function (result) {
                        if (result.isLiked) {
                            $('#post-like-' + String(post_id)).attr('src', "{{url_for('static', filename='svg/like-fill.svg')}}")
                        } else {
                            $('#post-like-' + String(post_id)).attr('src', "{{url_for('static', filename='svg/like.svg')}}")
                        }
                        update_post_like_count(post_id);
                    }
                });
                return false;
            } else {
                alert('로그인후 사용해주세요')
            }
        }

        function update_comment_like_count(comment_id) {
            $.ajax({
                url: "/user/comment/" + comment_id + "/like",
                type: "FETCH",
                dataType: "json",
                success: function (result) {
                    $('span#comment-like-button-' + String(comment_id)).text(String(result.count) + "명")
                }

            });
        }

        function update_comment_like_button(comment_id) {
            if (Boolean('{{current_user.is_authenticated}}')) {
                $.ajax({
                    url: "/user/comment/" + comment_id + "/like",
                    type: "POST",
                    dataType: "json",
                    success: function (result) {
                        if (result.isLiked) {
                            $('#comment-like-' + String(comment_id)).attr('src', "{{url_for('static', filename='svg/like-fill.svg')}}")
                        } else {
                            $('#comment-like-' + String(comment_id)).attr('src', "{{url_for('static', filename='svg/like.svg')}}")
                        }
                        update_comment_like_count(comment_id);
                    }
                });
                return false;
            } else {
                alert('로그인후 사용해주세요')
            }
        }
    </script>
    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Heej{% endblock %}
{% import "_macros.html" as macros %}
{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="my-3 p-3 bg-white rounded shadow-sm">
                {% if current_user.is_authenticated %}
                <div class="card-body">
                    <h5 class="card-title">{{current_user.name}}님!</h5>
                    <p class="card-text">
                        {{current_user.email}} <br>
                        가입일 : {{current_user.created_at|date}}
                    </p>
                    <a href="{{url_for('user.user_page', user_id=current_user.id)}}" class="btn btn-secondary">마이페이지</a>
                </div>
                {% else %}
                <div class="card-body">
                    <h5 class="card-title">로그인 해주세요</h5>
                    <a href="{{url_for('auth.login')}}">로그인하기</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-md-9">
            <div class="my-3 p-3 bg-white rounded shadow-sm">
                <h4 class="border-gray pb-2 mb-0">최근 게시글</h6>
                {% with end_point="main.index" %}
                    {% include 'user/_posts.html' %}
                {% endwith %}
            </div>
            {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, '.index') }}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}마이페이지{% endblock %}
{% block page_content %}
<div class="mypage row mt-5 mb-5">
	<div class="image col-md-2">
		<img class="img-fluid rounded-circle" src="{{url_for('static', filename='images/resources/detail-gold1.jpg')}}"
			data-holder-rendered="true">
	</div>
	<div class="content col-md-9">
		<div class="card shadow-sm">
			<div class="card-body">
				<h3 class="card-title pricing-card-title">&nbsp;{{user.name}}</h1>
					<small class="text-muted">가입일 : {{user.created_at|date}}</small><br>
					<small><img
							src="{{url_for('static', filename='svg/inbox.svg')}}">&nbsp;&nbsp;{{user.email}}</small>&nbsp;&nbsp;
					<small><img src="{{url_for('static', filename='svg/birth.svg')}}">&nbsp;&nbsp;{{user.birth|date('%Y년
						%m월 %d일') or '정보없음'}}</small><br>
					<small><img src="{{url_for('static', filename='svg/gender.svg')}}">&nbsp;&nbsp;
						{% if user.gender == 'F' %}
						여자
						{% elif user.gender == 'M' %}
						남자
						{% else %}
						정보없음
						{% endif %}
					</small>&nbsp;&nbsp;
					<small><img src="{{url_for('static', filename='svg/geo-alt.svg')}}">&nbsp;&nbsp;{{user.location or
						'정보없음'}}</small>&nbsp;&nbsp;
					<small><img src="{{url_for('static', filename='svg/job.svg')}}">&nbsp;&nbsp;{{user.job or
						'정보없음'}}</small>

					<ul class="list-unstyled mt-2">
						<li>{{ user.abount_me or ''}}</li>
					</ul>
					{% if current_user == user %}
					<a class="btn btn-outline-secondary" href="{{url_for('user.create_post')}}"><img
							src="{{url_for('static', filename='svg/pen.svg')}}" alt=""> 글쓰기</a>
					<a class="btn btn-outline-secondary" href="{{url_for('user.edit_profile')}}"><img
							src="{{url_for('static', filename='svg/person-lines-fill.svg')}}" alt=""> 프로필 편집</a>
					{% endif %}
			</div>
		</div>
	</div>
	<hr>
</div>
{% if user.posts.filter_by(deleted=False).all() %}
<nav>
	<div class="nav nav-tabs" id="nav-tab" role="tablist">
		<a {% if tab_status == 'post' %} class="nav-link active" {%else%} class="nav-link" {% endif %} href="{{url_for('user.update_tab_cookie', status='post', user_id=user.id)}}">게시글</a>
		<a {% if tab_status == 'like' %} class="nav-link active" {%else%} class="nav-link" {% endif %} href="{{url_for('user.update_tab_cookie', status='like', user_id=user.id)}}">좋아요</a>
	</div>
</nav>
<div class="row">
	<div class="myposts col-md-12">
		{% with end_point="user.user_page" %}
		{% include 'user/_posts.html' %}
		{% endwith %}
		{% if pagination %}
		<div class="pagination mt-3">
			{{ macros.pagination_widget(pagination, 'user.user_page', user_id=user.id) }}
		</div>
		{% endif %}
	</div>
</div>

{% else %}
게시글이 존재하지 않습니다.
{% endif %}
{% endblock %}